openapi: 3.0.3
info:
  title: Магазин медалей
  description: OpenAPI спецификация
  version: 0.0.2

paths:
  # товары
  /api/products:
    get:
      tags:
        - Товары
      summary: Метод получения списка товаров
      description: Получение списка товаров для отображения в компоненте каталога.
      operationId: getProducts
      responses:
        '200':
          description: Успешный ответ с получением списка товаров
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Products"
        default:
          description: Любой другой ответ с ошибкой
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/product/{id}:
    get:
      tags:
        - Товары
      summary: Метод получения конкретного товара
      operationId: getProduct
      parameters:
        - name: id
          in: path
          required: true
          description: Идентификатор товара
          schema:
            type: integer
          example: 1
      responses:
        '200':
          description: Успешный ответ с получением конкретного товара
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        default:
          description: Любой другой ответ с ошибкой
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  # параметры
  /api/parameters/label{parameterTuple}:
    get:
      tags:
        - Параметры товаров
      summary: Метод получения названий параметра и одного его значения
      operationId: getParameterLabels
      parameters:
        - name: parameterTuple
          in: path
          required: true
          description: Тип параметра
          schema:
            $ref: '#/components/schemas/ParameterTupleRequest'
      responses:
        '200':
          description: Успешный ответ с получением списка значений параметра товара
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParameterTupleResponse'
        default:
          description: Любой другой ответ с ошибкой
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  # корзина
  /api/cart/items{data}:
    get:
      tags:
        - Корзина
      summary: Метод получения списка всех товаров в корзине с текстовами обозначениями параметров товаров
      operationId: getCartItems
      parameters:
        - in: path
          name: data
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  type: integer
                example: [1, 2]
          required: true
          description: массив с идентификаторами товаров и параметрами товара (если они есть)
      responses:
        '200':
          description: Успешный ответ с получением списка товаров
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CartItemList"
        default:
          description: Любой другой ответ с ошибкой
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/cart/do-order:
    post:
      tags:
        - Корзина
      summary: Оформление заказа
      description: Передается JSON-объект с идентификаторами товаров, количеством и параметрами покупки
      operationId: doOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CartOrder"
      responses:
        '200':
          description: Клиентская часть не ждет ответа, предполагается, что будет редирект на страницу с оплатой

components:
  schemas:
    # товары каталога
    Product:
      type: object
      required:
        - id
        - name
        - description
        - price
        - url
        - image
        - parameters
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: 'Планка'
        description:
          type: string
          example: 'Планка с ореданми'
        price:
          type: integer
          example: 60
        url:
          type: string
          example: 'ссылка на детальную страницу'
        image:
          type: string
          example: 'https://some-url/image.jpg'
        imageAlt:
          type: string
          example: 'планка'
        sectionName:
          type: string
          example: 'Планки'
        parameters:
          $ref: '#/components/schemas/Parameters'

    Products:
      type: array
      items:
        $ref: '#/components/schemas/Product'
      example:
        - id: 1
          name: 'Планка'
          description: 'Планка с орденами'
          price: 100
          url: 'ссылка на детальную страницу'
          image: 'https://some-url/image.jpg'
          imageAlt: 'alt'
          sectionName: 'Планки'
        - id: 2
          name: 'Жетон'
          description: 'Жетон какой-то'
          price: 200
          image: 'https://some-url/image2.jpg'
          url: 'ссылка на детальную страницу'
          imageAlt: 'alt image text'
          sectionName: 'Жетоны'

    # параметры товаров
    Items:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          example: 1
        label:
          type: string
          example: 'Синий'
        image:
          type: string
          example: '/upload/image.png'
    ItemsCheckbox:
      type: array
      items:
        $ref: "#/components/schemas/Items"
      example:
        - id: 1
          label: 'На липучке'
          image: '/upload/image_1.png'
        - id: 2
          label: 'Без липучки'
          image: '/upload/image_2.png'
        - id: 14
          label: 'Другой какой-то тип'
          image: '/upload/image_14.png'
    ItemsSelect:
      type: array
      items:
        $ref: "#/components/schemas/Items"
      example:
        - id: 1
          label: 'Зеленый'
        - id: 2
          label: 'Черный'
    ParameterInput:
      type: object
      required:
        - label
        - items
      properties:
        name:
          type: string
          example: "number"
        type:
          type: string
          example: "input"
        label:
          type: string
          example: 'Номер, который нужно ввести'
        depends:
          type: object
          example: null
    ParameterCheckbox:
      type: object
      required:
        - label
        - items
      properties:
        name:
          type: string
          example: "base"
        type:
          type: string
          example: "checkbox"
        label:
          type: string
          example: 'Основа'
        depends:
          type: object
          example: null
        items:
          $ref: "#/components/schemas/ItemsCheckbox"
    ParameterSelect:
      type: object
      required:
        - label
        - items
      properties:
        name:
          type: string
          example: "base"
        type:
          type: string
          example: "checkbox"
        label:
          type: string
          example: 'Основа'
        depends:
          type: object
          example:
            base: [1, 2]
        items:
          $ref: "#/components/schemas/ItemsSelect"
    Parameters:
      type: array
      items:
        anyOf:
          - $ref: '#/components/schemas/ParameterInput'
          - $ref: '#/components/schemas/ParameterCheckbox'
          - $ref: '#/components/schemas/ParameterSelect'


    # кортежи для параметров
    ParameterTupleRequest:
      type: object
      required:
        - parameter
        - value
      properties:
        parameter:
          type: string
          example: "type"
        value:
          type: integer
          example: 33
    ParameterTupleResponse:
      type: object
      required:
        - parameter
        - value
      properties:
        parameter:
          type: string
          example: "Тип"
        value:
          type: string
          example: "Зеленый"

    # корзина
    CartItem:
      required:
        - id
        - name
        - description
        - price
        - url
        - image
        - parameterLabels
      allOf:
        - type: object
          properties:
            id:
              type: integer
              example: 1
            name:
              type: string
              example: 'Планка'
            description:
              type: string
              example: 'Планка с ореданми'
            price:
              type: integer
              example: 60
            url:
              type: string
              example: 'ссылка на детальную страницу'
            image:
              type: string
              example: 'https://some-url/image.jpg'
            imageAlt:
              type: string
              example: 'планка'
            sectionName:
              type: string
              example: 'Планки'
    CartItemList:
      type: array
      items:
        $ref: '#/components/schemas/CartItem'
      example:
        - id: 1
          name: 'Планка'
          description: 'Планка с орденами'
          price: 100
          url: 'ссылка на детальную страницу'
          image: 'https://some-url/image.jpg'
          imageAlt: 'alt'
          sectionName: 'Планки'
        - id: 2
          name: 'Жетон'
          description: 'Жетон какой-то'
          price: 200
          image: 'https://some-url/image2.jpg'
          url: 'ссылка на детальную страницу'
          imageAlt: 'alt image text'
          sectionName: 'Жетоны'

    # заказ
    CartOrderItem:
      type: object
      required:
        - id
        - count
      properties:
        id:
          type: integer
        count:
          type: integer
        parameters:
          type: object
          required:
            - parameter
            - value
          properties:
            parameter:
              type: string
              example: 'type'
            value:
              type: integer
              example: 1
    CartOrder:
      type: object
      properties:
        phone:
          type: string
          example: '88005553535'
        email:
          type: string
          example: 'billy_herrington@gachi.gov'
        products:
          type: array
          items:
            $ref: "#/components/schemas/CartOrderItem"
          example:
            - id: 1
              count: 4
              parameters:
                - parameter: 'color'
                  value: 1
            - id: 2
              count: 25
              parameters: []
            - id: 14
              count: 1
              parameters:
                - parameter: 'color'
                  value: 1
                - parameter: 'base'
                  name: 5
                - value: 'type'
                  parameter: 7

    # ошибки
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          example: 422
        message:
          type: string
          example: 'Ошибка загрузки'
