# Generated by Django 3.2.12 on 2023-07-03 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Callrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=80, verbose_name='Номер телефона')),
                ('dateandtame', models.DateTimeField(verbose_name='Дата и время')),
            ],
            options={
                'verbose_name': 'Заказ обратного звонка',
                'verbose_name_plural': 'Заказы обратного звонка',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Наименование вида товара')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Главное изображение вида товара')),
            ],
            options={
                'verbose_name': 'Вид товара',
                'verbose_name_plural': 'Виды товаров',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Categorymedals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Вид награды')),
            ],
            options={
                'verbose_name': 'Вид награды',
                'verbose_name_plural': 'Виды наград',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Вид параметра')),
                ('inputtype', models.CharField(blank=True, choices=[('1', 'checkbox'), ('2', 'inpuqt'), ('3', 'select')], max_length=20, verbose_name='Тип ввода')),
                ('label', models.CharField(max_length=180, verbose_name='Подпись')),
            ],
            options={
                'verbose_name': 'Вид параметра',
                'verbose_name_plural': 'Виды параметров',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Наименование товара')),
                ('image', models.ImageField(upload_to='products_imgs/', verbose_name='Главное изображение товара')),
                ('price', models.IntegerField(default=100, verbose_name='Цена')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='baseapp.categories', verbose_name='Категория')),
                ('medalcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorymedal', to='baseapp.categorymedals', verbose_name='Вид награды')),
                ('parameters', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter', to='baseapp.parameters', verbose_name='Параметр')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='product_imgs/', verbose_name='Дополнительное изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='baseapp.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'Дополнительное изображение',
                'verbose_name_plural': 'Дополнительные изображения',
            },
        ),
    ]
