# Generated by Django 3.2.12 on 2023-07-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Наименование основы(крепления)')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Изображение крепления')),
                ('requireColor', models.BooleanField(default=False, verbose_name='Нужен ли выбор цвета')),
            ],
            options={
                'verbose_name': 'Вид крепления',
                'verbose_name_plural': 'Виды креплений',
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='parameters',
            name='inputtype',
            field=models.CharField(blank=True, choices=[('1', 'checkbox'), ('2', 'input'), ('3', 'select')], max_length=20, verbose_name='Тип ввода'),
        ),
    ]
