# Generated by Django 3.2.12 on 2023-07-05 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_auto_20230703_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=50, verbose_name='Электронная почта')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата заказа')),
                ('sumcost', models.CharField(blank=True, max_length=50, verbose_name='Сумма заказа')),
                ('is_paid', models.BooleanField(default=False, verbose_name='оплачено')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Obtains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, max_length=700, null=True, verbose_name='Описание заказа')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='baseapp.orders', verbose_name='Заказ')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseapp.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
                'ordering': ['order'],
            },
        ),
    ]
