# Generated by Django 3.2.12 on 2023-06-17 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_auto_20230617_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorymedals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Вид награды')),
            ],
            options={
                'verbose_name': 'Вид награды',
                'verbose_name_plural': 'Виды наград',
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='baseapp.product', verbose_name='товар'),
        ),
        migrations.AddField(
            model_name='product',
            name='medalcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorymedal', to='baseapp.categorymedals', verbose_name='Вид награды'),
        ),
    ]
