# Generated by Django 3.2.12 on 2023-07-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_obtains_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='obtains',
            name='count',
            field=models.IntegerField(default=100, verbose_name='Количество'),
        ),
    ]
