# Generated by Django 3.2.12 on 2023-07-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0006_auto_20230708_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examples',
            name='about',
            field=models.TextField(max_length=180, verbose_name='Описание'),
        ),
    ]
