# Generated by Django 3.2.12 on 2023-06-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0006_auto_20230625_2058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameters',
            options={'verbose_name': 'Тип планки', 'verbose_name_plural': 'Типы Планок'},
        ),
        migrations.AddField(
            model_name='parameters',
            name='backcolor',
            field=models.BooleanField(default=False, verbose_name='Требуется запрос цвета подложки'),
        ),
        migrations.DeleteModel(
            name='Parameterstypes',
        ),
    ]
