# Generated by Django 3.2.12 on 2023-06-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0007_auto_20230625_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='needparameters',
            field=models.BooleanField(default=True, verbose_name='Запрашивать тип планки'),
        ),
    ]
