# Generated by Django 3.2.12 on 2023-07-03 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0008_product_needparameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='backcolor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_hit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_sale',
        ),
        migrations.AddField(
            model_name='parameters',
            name='inputtype',
            field=models.CharField(choices=[('1', 'Входная'), ('2', 'Межкомнатная')], default='1', max_length=20, verbose_name='Вид ввода'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='label',
            field=models.CharField(default='1', max_length=180, verbose_name='Выводимый текст'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='baseapp.product', verbose_name='Товар'),
        ),
    ]
