# Generated by Django 3.2.12 on 2023-07-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0009_auto_20230703_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='product',
        ),
        migrations.AddField(
            model_name='parameters',
            name='product',
            field=models.ManyToManyField(default=1, to='baseapp.Product', verbose_name='Товар'),
        ),
    ]
