# Generated by Django 3.2.12 on 2023-07-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0010_auto_20230703_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameters',
            options={'verbose_name': 'Параметр', 'verbose_name_plural': 'Параметры'},
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='needparameters',
        ),
        migrations.AddField(
            model_name='product',
            name='parametre',
            field=models.ManyToManyField(to='baseapp.Parameters', verbose_name='Параметры товара'),
        ),
    ]
