# Generated by Django 3.2.12 on 2023-07-03 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0011_auto_20230703_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/', verbose_name='Изображение параметра'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='inputtype',
            field=models.CharField(choices=[('1', 'Вводимый'), ('2', 'Выбор')], default='1', max_length=20, verbose_name='Вид ввода'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='label',
            field=models.CharField(max_length=180, verbose_name='Выводимый текст'),
        ),
        migrations.CreateModel(
            name='Subparameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='1', max_length=180, verbose_name='Выводимый текст')),
                ('image', models.ImageField(upload_to='imgs/', verbose_name='Изображение подпараметра')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.parameters', verbose_name='Параметр')),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметры',
            },
        ),
    ]
