# Generated by Django 3.2.12 on 2023-07-08 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paymentsystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photoorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='photoorders/', verbose_name='Фото заказа')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=50, verbose_name='Электронная почта')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paymentsystem.orders', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Заказ по фото',
                'verbose_name_plural': 'Заказы по фото',
                'ordering': ['order'],
            },
        ),
    ]
