# Generated by Django 3.2.12 on 2023-07-08 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentsystem', '0002_photoorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['-id'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='photoorder',
            name='email',
        ),
        migrations.RemoveField(
            model_name='photoorder',
            name='phone',
        ),
    ]
