# Generated by Django 3.2.12 on 2023-07-12 19:23

from django.db import migrations, models
import paymentsystem.utils


class Migration(migrations.Migration):

    dependencies = [
        ('paymentsystem', '0003_auto_20230708_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoorder',
            name='image',
            field=models.ImageField(blank=True, upload_to=paymentsystem.utils.get_rename, verbose_name='Фото заказа'),
        ),
    ]
